/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/balance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show balance */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["balance"];
                    };
                };
                /** @description balances not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/bank_accounts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list bank accounts */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["bank_account"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list banks */
        get: {
            parameters: {
                query?: {
                    apply_trader_filter?: components["parameters"]["apply_trader_filter_param"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            banks: components["schemas"]["bank"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/banks/show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show bank */
        get: {
            parameters: {
                query?: {
                    bank?: components["parameters"]["bank_param"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["bank"];
                    };
                };
                /** @description bank not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description invalid params */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/cashin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** initialize cashin operation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        amount: string;
                        kind: components["schemas"]["bank_account_kinds"];
                    };
                };
            };
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            value: string;
                            currency?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/cashin/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** cancel cashin operation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/cashin/{id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** confirm cashin operation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/cashout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** initialize cashout operation */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        amount: string;
                        wallet: string;
                    };
                };
            };
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/cashout/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** cancel cashout operation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list devices */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["device_statuses"][];
                    title?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["device"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** create device */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["device"];
                    };
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show device */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["device"];
                    };
                };
            };
        };
        /** update device */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                    };
                };
            };
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["device"];
                    };
                };
                /** @description device not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        post?: never;
        /** delete device */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description device not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** activate device */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description device not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** deactivate device */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description device not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/devices/{id}/healthcheck": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** touch device active status */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description device not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list disputes */
        get: {
            parameters: {
                query?: {
                    device_id?: string;
                    profile_id?: number;
                    requisite_id?: number;
                    requisite_type?: string;
                    from_date?: string;
                    to_date?: string;
                    min_amount?: number;
                    max_amount?: number;
                    order_number?: string;
                    api_payment_token?: string;
                    "status[]"?: components["schemas"]["dispute_statuses"][];
                    sort_field?: string;
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["dispute"][];
                        };
                        "text/csv": {
                            total_count: number;
                            list: components["schemas"]["dispute"][];
                        };
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
                            total_count: number;
                            list: components["schemas"]["dispute"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show dispute */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dispute"];
                    };
                };
            };
        };
        /** update dispute */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        status?: components["schemas"]["dispute_statuses"];
                        reasonComment?: string;
                        reasonCode?: string;
                    };
                };
            };
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description bad request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/sum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** disputes sum */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["balance_item"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/disputes/reasons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** reasons dispute */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["dispute_reasons_codes"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list feeds */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["feed_statuses"][];
                    "requisite_type[]"?: components["schemas"]["requisite_types"][];
                    "bank[]"?: (components["schemas"]["profile_banks"] | string)[];
                    amount_from?: number;
                    amount_to?: number;
                    "type[]"?: components["schemas"]["feed_types"][];
                    order_number?: string;
                    api_payment_token?: string;
                    created_at_from?: string;
                    created_at_to?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                    "device_id[]"?: string[];
                    profile_id?: number;
                    "requisite_id[]"?: number[];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["feed"][];
                        };
                        "text/csv": {
                            total_count: number;
                            list: components["schemas"]["feed"][];
                        };
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
                            total_count: number;
                            list: components["schemas"]["feed"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show feed */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["feed"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** approve feed */
        post: {
            parameters: {
                query?: {
                    trader_id?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}/decline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** decline feed */
        post: {
            parameters: {
                query?: {
                    trader_id?: number;
                };
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** upload documents for feed */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "multipart/form-data": {
                        /** Format: binary */
                        document: string;
                    };
                };
            };
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/sum": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** feeds sum */
        get: {
            parameters: {
                query?: {
                    created_at_from?: string;
                    created_at_to?: string;
                    "type[]"?: components["schemas"]["feed_types"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["balance_item"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/sum_profit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** feeds sum profit */
        get: {
            parameters: {
                query?: {
                    created_at_from?: string;
                    created_at_to?: string;
                    "type[]"?: components["schemas"]["feed_types"][];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["balance_item"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/activation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** activation status feed */
        get: {
            parameters: {
                query?: {
                    type?: components["schemas"]["feed_types"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            status: boolean;
                        };
                    };
                };
            };
        };
        put?: never;
        /** activate feed */
        post: {
            parameters: {
                query?: {
                    type?: components["schemas"]["feed_types"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/deactivation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** deactivate feed */
        post: {
            parameters: {
                query?: {
                    type?: components["schemas"]["feed_types"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/feeds/{id}/amobile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** amobile payout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/internal_transfers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** transfer all income to balance */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description when accounts not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list operations */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["feed_statuses"][];
                    type?: components["schemas"]["operation_types"][];
                    created_at_from?: string;
                    created_at_to?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["operation"][];
                        };
                        "text/csv": {
                            total_count: number;
                            list: components["schemas"]["operation"][];
                        };
                        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": {
                            total_count: number;
                            list: components["schemas"]["operation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/operations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show operation */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["operation"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create payment */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        token: string;
                        /** Format: float */
                        amount: number;
                        filtered_traders?: number[];
                        pay_expired_minutes?: number;
                        requisite_type?: components["schemas"]["requisite_types"];
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requisite"];
                    };
                };
                /** @description trader not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/payouts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** create payout */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        status: components["schemas"]["requisite_statuses"];
                        requisite_value: string;
                        card_holder?: string;
                        kind?: components["schemas"]["requisite_kinds"];
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            requisite_id?: number;
                        };
                    };
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list profiles */
        get: {
            parameters: {
                query?: {
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["profile"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** create profile */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        first_name: string;
                        last_name: string;
                        middle_name?: string;
                        phone?: string | null;
                        link?: string | null;
                        account_number?: string;
                        device_id?: string;
                        bank: string;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["profile"];
                    };
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show profile */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["profile"];
                    };
                };
            };
        };
        /** update profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        first_name: string;
                        last_name: string;
                        middle_name: string;
                        phone?: string | null;
                        link?: string | null;
                        account_number?: string;
                        device_id?: string;
                        bank: string;
                        note?: string;
                    };
                };
            };
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["profile"];
                    };
                };
                /** @description profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        post?: never;
        /** soft delete profile */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/block": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** block profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["profile"];
                    };
                };
                /** @description profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{id}/unblock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** unblock profile */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["profile"];
                    };
                };
                /** @description profile not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rates/{trader_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show rate */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description trader_id */
                    trader_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["rate"];
                    };
                };
                /** @description unprocessable entity */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list requisites */
        get: {
            parameters: {
                query?: {
                    "status[]"?: components["schemas"]["requisite_statuses"][];
                    device_id?: string;
                    requisite_value?: string;
                    per_page?: number;
                    page?: number;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["requisite"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requisites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** soft delete requisite */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description requisite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requisites/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** activate requisite */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description requisite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/requisites/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** deactivate requisite */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description requisite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/requisites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list requisites */
        get: {
            parameters: {
                query?: {
                    status?: components["schemas"]["requisite_statuses"];
                    device_id?: string;
                    requisite_value?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                };
                header?: never;
                path: {
                    profile_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["requisite"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** create requisite */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    profile_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        requisite_type: components["schemas"]["requisite_types"];
                        requisite_value: string;
                        card_holder?: string;
                        min_amount_float?: number;
                        max_amount_float?: number;
                        amount_limit_float?: number;
                        transaction_limit?: number;
                        transaction_delay?: number;
                        concurrent_transactions?: number;
                        deactivate_limit_reached?: boolean;
                        deactivate_dispute_present?: boolean;
                        concurrent_transactions_enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requisite"];
                    };
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/profiles/{profile_id}/requisites/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** update requisite */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    profile_id: number;
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        title: string;
                        requisite_type: components["schemas"]["requisite_types"];
                        requisite_value: string;
                        card_holder?: string;
                        min_amount_float?: number;
                        max_amount_float?: number;
                        amount_limit_float?: number;
                        transaction_limit?: number;
                        transaction_delay?: number;
                        concurrent_transactions?: number;
                        deactivate_limit_reached?: boolean;
                        deactivate_dispute_present?: boolean;
                        concurrent_transactions_enabled?: boolean;
                    };
                };
            };
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["requisite"];
                    };
                };
                /** @description requisite not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show search */
        get: {
            parameters: {
                query: {
                    search_query: string;
                };
                header?: {
                    "x-api-key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            disputes?: components["schemas"]["dispute"][];
                            feeds?: components["schemas"]["feed"][];
                            devices?: components["schemas"]["device"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show session and refresh expiry time */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description session found */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["session"];
                    };
                };
                /** @description session not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /** create session */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["session"];
                    };
                };
                /** @description input invalid */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["errors_object"];
                    };
                };
            };
        };
        /** destroys session */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description session destroyed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms_messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list sms messages */
        get: {
            parameters: {
                query?: {
                    uuid?: string;
                    profile_id?: number;
                    requisite_id?: number;
                    text?: string;
                    created_at_from?: string;
                    created_at_to?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            total_count: number;
                            list: components["schemas"]["sms_message"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms_messages.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list sms messages (CSV) */
        get: {
            parameters: {
                query?: {
                    uuid?: string;
                    profile_id?: number;
                    requisite_id?: number;
                    created_at_from?: string;
                    created_at_to?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        /** @description attachment filename */
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "text/csv": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms_messages.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** list sms messages (XLSX) */
        get: {
            parameters: {
                query?: {
                    uuid?: string;
                    profile_id?: number;
                    requisite_id?: number;
                    created_at_from?: string;
                    created_at_to?: string;
                    sort_field?: components["schemas"]["sort_fields"];
                    sort_direction?: components["schemas"]["sort_directions"];
                    per_page?: number;
                    page?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        /** @description attachment filename */
                        "Content-Disposition"?: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sms_messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** show sms message */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description successful */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["sms_message"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        bank_account: {
            id?: number;
            kind?: components["schemas"]["bank_account_kinds"];
            value?: string;
            currency?: string;
        };
        bank: {
            /** @example 1 */
            id?: number;
            names?: {
                ru?: string;
                en?: string;
            };
            logo?: string | null;
            /** @example eskhata */
            system_name?: string;
        };
        requisite: {
            id?: number;
            title: string;
            requisite_type: components["schemas"]["requisite_types"];
            requisite_value: string;
            card_holder?: string;
            min_amount_float?: number;
            max_amount_float?: number;
            status?: string;
            balance?: number;
            device_id?: string;
            device_name?: string;
            device_status?: components["schemas"]["device_statuses"];
            amount_limit_float?: number;
            transaction_limit?: number;
            transaction_delay?: number;
            daily_transactions?: number;
            daily_amount?: number;
            concurrent_transactions?: number;
            deactivate_limit_reached?: boolean;
            deactivate_dispute_present?: boolean;
            concurrent_transactions_enabled?: boolean;
            created_at?: string;
        };
        profile: {
            id?: number;
            title?: string;
            first_name?: string;
            last_name?: string;
            middle_name?: string;
            phone?: string | null;
            link?: string | null;
            device_id?: string;
            device_name?: string;
            device_status?: components["schemas"]["device_statuses"];
            account_number?: string | null;
            bank?: string;
            note?: string | null;
            blocked?: boolean;
            created_at?: string;
            requisites_count?: number;
            requisites_types?: components["schemas"]["requisite_types"][];
        };
        device: {
            id?: string;
            title?: string;
            status?: components["schemas"]["device_statuses"];
            created_at?: string;
            qr_code?: string | null;
            list?: components["schemas"]["profile"][];
        };
        dispute: {
            id?: number;
            status?: components["schemas"]["dispute_statuses"];
            amount?: number;
            currency?: string;
            gateway_amount?: number;
            gateway_currency?: string;
            commission_provider_amount?: number;
            payments_info?: {
                id?: number;
                amount?: number;
                currency?: string;
                gateway_amount?: number;
                gateway_currency?: string;
                type?: string;
                token?: string;
                target_currency_rate?: number;
            }[] | null;
            created_at?: string | null;
            updated_at?: string | null;
            bank_name?: components["schemas"]["profile_banks"] | string;
            requisite?: components["schemas"]["requisite"];
            documents?: {
                url?: string;
            }[];
            requisite_type?: string;
            device?: components["schemas"]["device"];
            feed_id?: number;
            order_number?: string;
            api_payment_token?: string;
            comment?: string;
            reason_code?: string;
        };
        balance_item: {
            amount?: number;
            gateway_amount?: number;
            currency?: string;
            gateway_currency?: string;
        };
        operation: {
            id?: number;
            created_at?: string | null;
            status?: components["schemas"]["feed_statuses"];
            amount?: string | null;
            type?: components["schemas"]["operation_types"];
            hash?: string | null;
            address?: string | null;
            from_account?: string | null;
            to_account?: string | null;
            currency?: string | null;
            gateway_currency?: string | null;
            gateway_amount?: number | null;
        };
        feed: {
            id?: number;
            api_payment_token?: string | null;
            order_number?: string | null;
            created_at?: string | null;
            updated_at?: string | null;
            requisite_id?: number | null;
            commission_provider_amount?: string | null;
            status?: components["schemas"]["feed_statuses"];
            requisite_type?: components["schemas"]["requisite_types"];
            amount?: string | null;
            currency?: string | null;
            type?: components["schemas"]["feed_types"];
            gateway_currency?: string | null;
            gateway_amount?: number | null;
            currency_rate?: number | null;
            full_name?: string;
            can_amobile_payout?: boolean;
            reference?: string;
            bank?: components["schemas"]["profile_banks"] | string;
            requisite_data?: string;
            /**
             * @example init
             * @enum {string}
             */
            verification?: "init" | "pending" | "process" | "approved" | "declined";
            documents?: string[];
        };
        session: {
            session_token?: string;
            session_expires?: string;
            status?: components["schemas"]["session_statuses"];
            created_at?: string;
            profile_id?: number;
            web_site?: string | null;
        };
        sms_message: {
            id?: number;
            amount?: number;
            currency?: string;
            uuid?: string;
            text?: string;
            from_data?: string;
            sms_type?: components["schemas"]["requisite_types"];
            created_at?: string;
            delivery_type?: string;
            delivery_time?: string;
            token?: string;
            device_name?: string;
        };
        balance: {
            main?: components["schemas"]["balance_item"];
            deposit?: components["schemas"]["balance_item"];
            income?: components["schemas"]["balance_item"];
            commissions?: {
                payin?: components["schemas"]["balance_item"];
                payout?: components["schemas"]["balance_item"];
            };
        };
        rate: {
            message?: string;
            rate?: number;
            result?: string;
        };
        /** @enum {string} */
        device_statuses: "active" | "stopped" | "unregistered";
        /** @enum {string} */
        dispute_statuses: "pending" | "approved" | "declined";
        dispute_reasons_codes: components["schemas"]["dispute_reasons_codes_item"][];
        dispute_reasons_codes_item: {
            code: string;
            name: {
                [key: string]: string;
            };
        };
        /** @enum {string} */
        profile_banks: "sberbank" | "raiffeisen" | "tbank" | "uralsib" | "alfabank" | "sovcombank" | "humocard" | "humo" | "uzcard" | "tbc" | "bog" | "otp" | "psb" | "yandex" | "mts" | "vtb" | "vodafone" | "ubrr" | "instapays" | "a-mobile" | "blanc" | "oriyonbonk" | "amonat" | "eskhata" | "spitamen" | "bank_account" | "attijiari_wafa_bank" | "khan_bank" | "adcb" | "mashreq_bank" | "fab" | "adib" | "nbd" | "al_rahji_bank" | "ila_bank" | "mercado_pago" | "lemon_cash" | "ripio" | "neft" | "imps" | "bt" | "state_bank_of_india" | "hdfc_bank" | "idfc_bank" | "punjab_national_bank" | "rbl_bank" | "axis_bank" | "kotak_bank" | "icici_bank" | "au_small_finance_bank" | "indus_bank" | "yes_bank" | "fino_payment_bank" | "canara_bank" | "bank_of_baroda" | "paytm" | "phonepe" | "google_pay" | "mobikwik" | "freecharge" | "whatsapp_pay" | "bhim_upi";
        /** @enum {string} */
        requisite_kinds: "pay" | "payout";
        /** @enum {string|null} */
        requisite_statuses: "active" | "stopped" | "blocked" | null;
        /** @enum {string} */
        bank_account_kinds: "main" | "deposit";
        /** @enum {string} */
        balance_kinds: "main" | "income" | "deposit";
        /** @enum {string} */
        feed_statuses: "pending" | "approved" | "declined";
        /** @enum {string|null} */
        feed_types: "PayinRequest" | "PayoutRequest" | "DisputeRequest" | "Feed" | null;
        /** @enum {string|null} */
        operation_types: "CashinRequest" | "CashoutRequest" | "PayRequest" | null;
        /** @enum {string|null} */
        requisite_types: "sbp" | "card" | "account" | "link" | null;
        /** @enum {string} */
        session_statuses: "created" | "expired" | "deleted";
        /** @enum {string} */
        sort_fields: "created_at";
        /** @enum {string} */
        sort_directions: "asc" | "desc";
        errors_object: {
            errors?: {
                [key: string]: unknown[];
            };
        };
    };
    responses: never;
    parameters: {
        bank_param: string;
        apply_trader_filter_param: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
